### ISSUE TITLE
New window animation stuttering

### ISSUE THREAD

**Issue by celestomm** [linux-is-awesome/gnome_extension_rocketbar#3]
Whenever I open a new window whilst having this extension enable, the opening animation stutters.
I tried deactivating my other extensions and the issue stayed so it probably is caused by this one.
Maybe it's just to heavy on the system or something ?

**Comment by ChepKun** [comment]
Hey!
Do you have this issue with every window you open?
Can you please run the script below in a terminal and attach the output?
`(for i in $(dconf list /org/gnome/shell/extensions/rocketbar/); do echo "$i:" $(dconf read /org/gnome/shell/extensions/rocketbar/$i); done)  `
Also before opening a new window run `journalctl -f -o cat /usr/bin/gnome-shell` in a terminal window and attach the output here. Thanks!

**Comment by ChepKun** [comment]
Also would be great if you could run neofetch/screenfetch/or so... and attach the output here just to give me an idea of your system specs.

**Comment by celestomm** [comment]
Hello,
Yes the stutter happens everytime I open a new window

Here are the outputs of the commands/scripts you asked me to run :

1 - `❯ (for i in $(dconf list /org/gnome/shell/extensions/rocketbar/); do echo "$i:" $(dconf read /org/gnome/shell/extensions/rocketbar/$i); done)`
```
appbutton-backlight: false
appbutton-enable-indicators: false
appbutton-enable-notification-badges: true
appbutton-enable-tooltips: true
hotcorner-enable-in-fullscreen: false
overview-kill-dash: false
panel-menu-require-click: false
taskbar-isolate-workspaces: true
taskbar-position: 'left'
taskbar-preserve-position: false
taskbar-show-favorites: false
```


2 - `❯ journalctl -f -o cat /usr/bin/gnome-shell`
This came directly after I entered the command prompt
```
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Could not create transient scope for PID 6797: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 6797 does not exist.
Could not create transient scope for PID 6813: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 6813 does not exist.
Could not create transient scope for PID 6862: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 6862 does not exist.
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Could not create transient scope for PID 7376: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 7376 does not exist.
Could not create transient scope for PID 7391: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 7391 does not exist.
Could not create transient scope for PID 7448: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 7448 does not exist.
```
This line was added after I opened the fedora app store application
```
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
```
These three lines were added after I opened [tidal-hifi](https://github.com/Mastermindzh/tidal-hifi)
```
Could not create transient scope for PID 8759: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 8759 does not exist.
Could not create transient scope for PID 8774: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 8774 does not exist.
Could not create transient scope for PID 8819: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 8819 does not exist.
# Some applications (including firefox) did not trigger the addition of a new line upon opening them
```


3 - `❯ neofetch`
```
             .',;::::;,'.                celeri@Tronc 
         .';:cccccccccccc:;,.            ------------ 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 36 (Workstation Editi 
    .:cccccccccccccccccccccccccc:.       Host: HP Pavilion Laptop 14-dv0xxx 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 5.18.11-200.fc36.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 23 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2329 (rpm), 19 (flatpak) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: zsh 5.8.1 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 1920x1080 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 42.3.1 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Adwaita-dark [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Papirus [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: gnome-terminal 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: 11th Gen Intel i7-1165G7 (8) @ 4. 
:cccccccccccccccccccccccccccc:'.         GPU: Intel TigerLake-LP GT2 [Iris Xe G 
.:cccccccccccccccccccccc:;,..            Memory: 3031MiB / 15666MiB 
  '::cccccccccccccc::;,.
                                                                 
```

**Comment by ChepKun** [comment]
Are you on Wayland or X11?
Actually I see nothing interesting in debug logs... so let me run Fedora and see if I can reproduce it

**Comment by celestomm** [comment]
I'm on Wayland but after trying it with Xorg I got the same issue

**Comment by ChepKun** [comment]
Well I guess I'm able to reproduce some kind of stuttering using Fedora 36 live mode when Firefox window is opening and the extension is enabled. Not sure if it is the same stuttering... because App Store window animation is really smooth... 
The are two possible reasons for that I can think about right now: 
- app button animation when a new button gets created, it's a simple one but maybe there is any problem in gnome shell/gpu driver/etc that causes stuttering because of multiple animations are running simultaneously
- code for updating window icon geometry probably... it's not resource heavy, especially for a single window, but worth to check if it's not causing any issues.

So I'm gonna spend more time digging into the possible reason for that.

**Comment by ChepKun** [comment]
@celestomm I can confirm that I was able to reproduce this issue. Seems like it happens mostly because of a dominant color feature that is always enabled behind the scene regardless of settings (Ooops). Also in my case noticeable stuttering only happens when power profile is set to power saver, with balanced power or performance profile animations look smooth. And I'm unable to reproduce it using Manjaro + X11 + nvidia gpu, so I'm going to use Fedora and intel gpu for testing.

In case you would like to test a temporary workaround, please comment out the code below:
![image](https://user-images.githubusercontent.com/5459599/180331716-e5ce4021-a22c-46be-acd4-9727d8e19e53.png)
inside this file ~/.local/share/gnome-shell/extensions/rocketbar@chepkun.github.com/ui/appButton.js
do log out -> log in and see if it helps, thanks!

**Comment by celestomm** [comment]
This solved my issue !
I wasn't using the dominant color option anyway so that's a win for me I guess.
For the power profile thing I'm always on balanced power so... maybe it's an issue related to my computer or something idk.
Anyway thank you very much ! :)

**Comment by ChepKun** [comment]
Fix for the bug is gonna be included in the next release
