### ISSUE TITLE
GNOME 45 Compatibility

### ISSUE THREAD

**Issue by Exponential-Workload** [linux-is-awesome/gnome_extension_rocketbar#33]
Recently, GNOME 45 released, which broke this. Having this work on GNOME 45 would be great

**Comment by laurentlbm** [comment]
I really like this extension, so I have started porting the code for GNOME 45. I got it to the point where it works (at least for me), except for the preferences, which I haven't fixed yet. 
You can download the source and run the `install` script to use it: https://github.com/laurentlbm/gnome-rocketbar/

I was hoping to port the code quickly, but found it more difficult than I anticipated. In part because GNOME 45 made a pretty significant breaking change to extensions (see [Extensions in GNOME 45](https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/)), but also because my knowledge of GNOME and extensions is pretty limited...

**Comment by ChepKun** [comment]
@Exponential-Workload 
@laurentlbm
Hey! Unfortunately, I don't have enough time now to work on this, but I still have plans to release a new version by the end of this year. Code for the new version is in `experimental` branch and it should be semi-compatible with Gnome 45, but I haven't tested it yet, still on Gnome 43, hehe. I'll get back to development of the extension as soon as I can, promise you.

**Comment by laurentlbm** [comment]
@ChepKun That's fine, I just want a working version in the meantime. I don't mind patching it if it isn't too difficult. If I can finish the work, would you accept a PR and publish a new version of the extension for GNOME 45?

FYI, the `experimental` branch will also need to be ported to 45. They changed how imports function, so extensions for GNOME 44 and below aren't compatible with those for GNOME 45, and vice-versa.

BTW, thanks for the extension, it's very useful. I used Pop Shell for a long time, but it tried to do too much and I often encountered bugs.
